### ISSUE TITLE
how to deploy to heroku?

### ISSUE THREAD

**Issue by askfriends** [kernoeb/Telegramusic#1]
can we deploy to heroku?
if yes than p;lease add instructions in readme.
thanks

**Comment by kernoeb** [comment]
Hello,
In theory, just create a Procfile with `worker: python3 main.py`, and add necessary environment variables in Heroku, it should work!
I'll update the readme later, and maybe add a "deploy to heroku" button
You can create a pull request for that if you want :+1: 
(please confirm me that it works so I can close the PR)

**Comment by askfriends** [comment]
> Hello, In theory, just create a Procfile with `worker: python3 main.py`, and add necessary environment variables in Heroku, it should work! I'll update the readme later, and maybe add a "deploy to heroku" button You can create a pull request for that if you want 👍 (please confirm me that it works so I can close the PR)

Thanks for the swift response.
and im noob so cant do that myself, will be waiting for ur update in readme.
deploy to heroku button will be of much help.
btw can u add google drive support? all the songs will be uploaded to google drive.

**Comment by kernoeb** [comment]
Okay, well, I just added the button
I didn't try it, I don't use Heroku anymore, I'm waiting for your tests ! 
Thanks

**Comment by kernoeb** [comment]
(PS : you maybe have to manually start the Dyno in Heroku)

**Comment by kernoeb** [comment]
I'm closing the issue, re-open it if you need
