### ISSUE TITLE
arl issue

### ISSUE THREAD

**Issue by DontJer** [kernoeb/Telegramusic#10]
Hey, is there any solution? I checked ARL many times and test others and still same error:
telegramusic-worker-1  | Traceback (most recent call last):
telegramusic-worker-1  |   File "/usr/src/app/./main.py", line 49, in <module>
telegramusic-worker-1  |     download = deezloader_async.DeeLogin(os.environ.get('DEEZER_TOKEN'))
telegramusic-worker-1  |   File "/usr/local/lib/python3.9/site-packages/module_wrapper/__init__.py", line 135, in __new__
telegramusic-worker-1  |     original_obj_object = cls._original_obj(*args, **kwargs)
telegramusic-worker-1  |   File "/usr/local/lib/python3.9/site-packages/deezloader/deezloader/__init__.py", line 45, in __init__
telegramusic-worker-1  |     self.__gw_api = API_GW(arl = arl)
telegramusic-worker-1  |   File "/usr/local/lib/python3.9/site-packages/deezloader/deezloader/deegw_api.py", line 48, in __init__
telegramusic-worker-1  |     cls.__refresh_token()
telegramusic-worker-1  |   File "/usr/local/lib/python3.9/site-packages/deezloader/deezloader/deegw_api.py", line 164, in __refresh_token
telegramusic-worker-1  |     cls.am_I_log()
telegramusic-worker-1  |   File "/usr/local/lib/python3.9/site-packages/deezloader/deezloader/deegw_api.py", line 191, in am_I_log
telegramusic-worker-1  |     raise BadCredentials(arl = cls.__arl)
telegramusic-worker-1  | deezloader.exceptions.BadCredentials: Wrong token: 25d9ddf470577c8f42b9393e9fe99586dddb7113111566b8255509bff5ad6d23466a.......... :(
telegramusic-worker-1 exited with code 1
telegramusic-worker-1  | Traceback (most recent call last):
telegramusic-worker-1  |   File "/usr/src/app/./main.py", line 49, in <module>
telegramusic-worker-1  |     download = deezloader_async.DeeLogin(os.environ.get('DEEZER_TOKEN'))
telegramusic-worker-1  |   File "/usr/local/lib/python3.9/site-packages/module_wrapper/__init__.py", line 135, in __new__
telegramusic-worker-1  |     original_obj_object = cls._original_obj(*args, **kwargs)
telegramusic-worker-1  |   File "/usr/local/lib/python3.9/site-packages/deezloader/deezloader/__init__.py", line 45, in __init__
telegramusic-worker-1  |     self.__gw_api = API_GW(arl = arl)
telegramusic-worker-1  |   File "/usr/local/lib/python3.9/site-packages/deezloader/deezloader/deegw_api.py", line 48, in __init__
telegramusic-worker-1  |     cls.__refresh_token()
telegramusic-worker-1  |   File "/usr/local/lib/python3.9/site-packages/deezloader/deezloader/deegw_api.py", line 164, in __refresh_token
telegramusic-worker-1  |     cls.am_I_log()
telegramusic-worker-1  |   File "/usr/local/lib/python3.9/site-packages/deezloader/deezloader/deegw_api.py", line 191, in am_I_log
telegramusic-worker-1  |     raise BadCredentials(arl = cls.__arl)
telegramusic-worker-1  | deezloader.exceptions.BadCredentials: Wrong token: 25d9ddf470577c8f42b9393e9fe99586dddb7113111566b8255509bff5ad6d23466a5....... :(

**Comment by kernoeb** [comment]
Hi ! 
That's weird, I actually changed my ARL cookie yesterday and it worked

Did it work before ?

**Comment by DontJer** [comment]
It's the first time I put arl in env file. Is that need any decode or sth like that?

**Comment by kernoeb** [comment]
The `token.env` file should look like this 

![image](https://github.com/kernoeb/Telegramusic/assets/24623168/dfc1f5e2-57b6-47e4-b454-1039896ee253)

From this cookie :

![image](https://github.com/kernoeb/Telegramusic/assets/24623168/2aa5b7fd-7365-4871-9aa4-253f4f01ba07)

This configuration works for me, maybe try to logout/log in on Deezer and try again ?

**Comment by DontJer** [comment]
~~I logged out and logging in again but still the same issue. the token.env file looks exact like you sent.~~ I tested it on another server and get fixed. Can somehow when one music searched into bot send music directly (not link)?for example if user a search  music x one time and bot download music next time user a,b or others search music x get downloaded music not solid link,

**Comment by kernoeb** [comment]
The search and link ways are working the same, as the search option is converted to a link/id, so I don't think it could be related

One possibility is that the error (wrong token) is not explicit and real, and it just doesn't work cause the server IP is banned, a firewall is set, or something like that

Maybe you can try accessing deezer API manually or using deezloader in command line to debug
