### ISSUE TITLE
No module named 'deezloader.deezloader'

### ISSUE THREAD

**Issue by alefvanoon** [kernoeb/Telegramusic#3]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    import deezloader.deezloader
ModuleNotFoundError: No module named 'deezloader.deezloader'

**Comment by kernoeb** [comment]
Hello.
Are you using the docker way ?

**Comment by kernoeb** [comment]
It's easier to use Docker here, less buggy, and really faster
Otherwise, you have to do `python3 -m pip install -r requirements.txt` to install modules

**Comment by alefvanoon** [comment]
Hey, thanks for your reply 
No, i'm install without docker...
I was installed all requirements.

**Comment by kernoeb** [comment]
> Hey, thanks for your reply 
> No, i'm install without docker...
> I was installed all requirements.

I'll check this tonight, maybe try to use docker or check the dockerfile to see needed steps
I'll test it then I'm going to update the readme

**Comment by kernoeb** [comment]
Hey, I'm not able to reproduce your issue
Try to do this (you can found theses steps in the Dockerfile)

```
## ffmpeg install
sudo apt update && sudo apt install -y ffmpeg

## Install requirements
python3 -m pip install -r requirements.txt

## Update Youtube DL to a better working version
cd /tmp && wget https://github.com/ytdl-org/youtube-dl/archive/d69983a8756fa75e16606bcd1b2ba50ec115ed16.zip && unzip d69983a8756fa75e16606bcd1b2ba50ec115ed16.zip && cd youtube-dl-d69983a8756fa75e16606bcd1b2ba50ec115ed16 && python3 -m pip install .

## Remove FLAC
-- You maybe have to change the /usr/local/lib part
mv ./fixes/deezer_settings.py /usr/local/lib/python3.9/site-packages/deezloader/deezloader/deezer_settings.py

## Run
python3 main.py
