### ISSUE TITLE
aioify error

### ISSUE THREAD

**Issue by fokoamartin** [kernoeb/Telegramusic#5]
heroku deploy failed

       ERROR: Could not find a version that satisfies the requirement aioify==0.4.1 (from versions: 0.1.3, 0.2.0, 0.3.1, 0.3.2, 0.4.0)
       ERROR: No matching distribution found for aioify==0.4.1
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by kernoeb** [comment]
Hello
That's weird

![image](https://user-images.githubusercontent.com/24623168/164201974-07c28836-b384-4ee3-bf87-39908a4beaed.png)

aiofy 0.4.1 exists

I'll try to reproduce your issue after work

**Comment by kernoeb** [comment]
Okay, I think it's related to Python version, let me fix this

**Comment by kernoeb** [comment]
It's fixed! Switched to Python 3.9.7 version for Heroku.
I don't use Heroku, I prefer the Docker way
Please confirm me that is works :)

**Comment by fokoamartin** [comment]
Yes it works now. Thank you

**Comment by kernoeb** [comment]
Cool!
