### ISSUE TITLE
Error Install on arm64 VPS

### ISSUE THREAD

**Issue by vishnoe115** [kernoeb/Telegramusic#7]
I was trying to install on arm64 aarch64 VPS. and got this kind error while deploying.  do you know any clue how to fix it?
NOTE: I was deploying on VPS by `docker-compose up --build` using repo from here https://github.com/kernoeb/Telegramusic/issues/4#issuecomment-1029236678

![image](https://user-images.githubusercontent.com/54537571/191971365-d6d503c3-3c33-4970-a697-08270bc2de17.png)

**Comment by kernoeb** [comment]
Hello, well that's weird,

I think I can try to reproduce this behavior on my m1 pro, it's an arm64

I'm currently at work, I'll check this asap, I'll keep you up !

**Comment by vishnoe115** [comment]
> Hello, well that's weird,
> 
> I think I can try to reproduce this behavior on my m1 pro, it's an arm64
> 
> I'm currently at work, I'll check this asap, I'll keep you up !

thank you. will waiting it patiently, also I was trying this from your reference, it's kinda same. https://github.com/kernoeb/Telegramusic/issues/4#issuecomment-1029239359

my vps environment: ubuntu 22.04 - arm64/v8 (oracle)

**Comment by vishnoe115** [comment]
> Hello, well that's weird,
> 
> I think I can try to reproduce this behavior on my m1 pro, it's an arm64
> 
> I'm currently at work, I'll check this asap, I'll keep you up !

sorry bro my bad. it works. actually, just to making sure.

![image](https://user-images.githubusercontent.com/54537571/191992668-84768659-b0c0-4edc-a315-714525216e28.png)

but,  I tried wrong repo from here to try get FLAC
your repo actually fine, in arm64, but can't get FLAC, tried with this repo https://github.com/kernoeb/Telegramusic/issues/4#issuecomment-1029239359 got error like above.

**Comment by kernoeb** [comment]
I'm not sure but I think FLAC needs a premium deezer account, so I disabled this feature

If FLAC is enabled, it'll be bad FLAC quality (mp3 to flac converted), so I think it's a little bit useless

**Comment by vishnoe115** [comment]
> I'm not sure but I think FLAC needs a premium deezer account, so I disabled this feature
> 
> If FLAC is enabled, it'll be bad FLAC quality (mp3 to flac converted), so I think it's a little bit useless

yeah, I have premium deezer account for it, is there a way to get enable flac with this repo? would u give a clue or something? thanks before

**Comment by kernoeb** [comment]
First, in the Dockerfile I explicitely disabled FLAC, to avoid errors (temporarily)

Second, I think the Python script would not work directly with FLAC if we re-enable it, as it uses mp3 detection (for song duration, tags, etc), so it would need to rewrite this part of the code for FLAC too... Maybe not hard, but I don't have a premium account to test it, if you can make a PR, it would be awesome 👌

Third, it would need a deploy parameter to explictely disable mp3 and only use FLAC (an option saved in a database for each user is a bit overkill)

**Comment by vishnoe115** [comment]
oh okay bro, I thought it's simple but seems it is not, if rewrite code need effort and much time, so leave it as it has, sorry bro.
